### ISSUE TITLE
Who is target audience?

### ISSUE THREAD

**Issue by CasperStaahl** [P6-AAU-23/other#11]

**Comment by CasperStaahl** [comment]
The target audience is presenters, for example a lecturer at a university.

The presenter has the following goals:
- Wants to use a physical medium (like a whiteboard, blackboard, or piece of paper) for presentation
- Wants the advantages of digital media (save, edit, stream etc.)
- Wants minimal cost of implementing the system
- Wants a product that is useable by the average user
- Wants to convey information, with a goal of information retention

**Comment by CasperStaahl** [comment]
The target audience is presenters, for example a lecturer at a university.

The presenter has the following goals:
- Wants to use a physical medium (like a whiteboard, blackboard, or piece of paper) for presentation
- Wants the advantages of digital media (save, edit, stream etc.)
- Wants minimal cost of implementing the system
- Wants a product that is useable by an **advanced user**
- Wants to convey information, with a goal of information retention

**Comment by RedToad0** [comment]
**Consider** 
Alternative target audiences such as, end users (for example students) or experienced IT users. 

**_AFTER_ choosing target audience**
Looking only and only at the current implementation which features and design choices relates to target audience and which does not?
For next and future sprints which potential improvements are most essential to our audience? (possibly ranking system?)
What is our desired end product for this audience? What is MVP?

**Comment by CasperStaahl** [comment]
The average presenter with the following goals: 
- Wants to use a physical medium (whiteboard, blackboard, or piece of paper) for presentation 
- Wants the advantages of digital media (save, edit, stream etc.) 
- Wants minimal cost of implementing the system 
- Wants a product that is useable by the average user 
- Wants to convey information, with a goal of information retention 

 

The advanced presenter with the following goals:  
- Wants to use a physical medium (whiteboard, blackboard, or piece of paper) for presentation 
- Wants the advantages of digital media (save, edit, stream etc.) 
- Wants minimal cost of implementing the system 
- Wants a product that is useable by an advanced user 
- Wants to convey information, with a goal of information retention 

 

The audience with the following goals: 
- Wants an aid for a physical medium (whiteboard, blackboard, or piece of paper) in a presentation with a goal of information retention. (The presentation can both be remote or in person) 
- Wants minimal cost of implementing the system 
- Wants a product that is useable by the average user
