### ISSUE TITLE
How will the server and client communicate?

### ISSUE THREAD

**Issue by CasperStaahl** [P6-AAU-23/other#2]

**Comment by miniJmo** [comment]
maybe it is possible with JSON files, but it might be too slow

**Comment by RedToad0** [comment]
Kan man ikke bare sende MAT objs og så have en built in interpeter på hver side?

**Comment by RedToad0** [comment]
https://stackoverflow.com/questions/33685266/what-is-the-best-way-to-transfer-a-cvmat-object-between-different-processes

**Comment by CasperStaahl** [comment]
This is exactly what we are drying to do:
https://stackoverflow.com/questions/45993828/get-videostream-from-rtmp-to-opencv

**Comment by CasperStaahl** [comment]
> This is exactly what we are drying to do: https://stackoverflow.com/questions/45993828/get-videostream-from-rtmp-to-opencv

Java implementation here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java

**Comment by CasperStaahl** [comment]
We will be using rtmp!
